
package com.service.ws;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "WheatherServiceImplService", targetNamespace = "http://ws.service.com/", wsdlLocation = "http://localhost:8080/SOAPProvider/ws?wsdl")
public class WheatherServiceImplService
    extends Service
{

    private final static URL WHEATHERSERVICEIMPLSERVICE_WSDL_LOCATION;
    private final static WebServiceException WHEATHERSERVICEIMPLSERVICE_EXCEPTION;
    private final static QName WHEATHERSERVICEIMPLSERVICE_QNAME = new QName("http://ws.service.com/", "WheatherServiceImplService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/SOAPProvider/ws?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        WHEATHERSERVICEIMPLSERVICE_WSDL_LOCATION = url;
        WHEATHERSERVICEIMPLSERVICE_EXCEPTION = e;
    }

    public WheatherServiceImplService() {
        super(__getWsdlLocation(), WHEATHERSERVICEIMPLSERVICE_QNAME);
    }

    public WheatherServiceImplService(WebServiceFeature... features) {
        super(__getWsdlLocation(), WHEATHERSERVICEIMPLSERVICE_QNAME, features);
    }

    public WheatherServiceImplService(URL wsdlLocation) {
        super(wsdlLocation, WHEATHERSERVICEIMPLSERVICE_QNAME);
    }

    public WheatherServiceImplService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, WHEATHERSERVICEIMPLSERVICE_QNAME, features);
    }

    public WheatherServiceImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public WheatherServiceImplService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns WheatherService
     */
    @WebEndpoint(name = "WheatherServiceImplPort")
    public WheatherService getWheatherServiceImplPort() {
        return super.getPort(new QName("http://ws.service.com/", "WheatherServiceImplPort"), WheatherService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns WheatherService
     */
    @WebEndpoint(name = "WheatherServiceImplPort")
    public WheatherService getWheatherServiceImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://ws.service.com/", "WheatherServiceImplPort"), WheatherService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (WHEATHERSERVICEIMPLSERVICE_EXCEPTION!= null) {
            throw WHEATHERSERVICEIMPLSERVICE_EXCEPTION;
        }
        return WHEATHERSERVICEIMPLSERVICE_WSDL_LOCATION;
    }

}
